package constants;

public enum StatusJogo {
	AGUARDANDO_JOGADORES, JOGO_INICIADO, AGUARDANDO_JOGADA, JOGO_ENCERRADO, PROCESSANDO_JOGADA, AGUARDANDO_REMATCH, PRONTO_PARA_INICIAR, VERIFICA_PRONTO, VALIDA_REMATCH
}
